# circleci does not support version 3.3 ~
version: "3.2"
services:
  app:
    container_name: "oilking"
    env_file: ".env"
    build:
        context: "./app"
        dockerfile: "Dockerfile"
    ports:
      - "8083:8083"
    restart: always